In [23]:
#Задание 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

import numpy as np

N = 10
array_desc = np.sort(np.arange(0, N))[::-1]

array_desc

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [62]:
#Задание 2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

N = 13
matrix = np.diag(np.sort(np.arange(0, N, 3))[::-1], k=0)
print(matrix)
sum_diag = sum(list(sum(matrix)))
print(sum_diag)

[[12  0  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0  0]]
30


In [66]:
# Задание 3. Решите систему уравнений

#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

from numpy import linalg

# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# значения в правой части уравнения

b = np.array( [4, 12, -3] )

# решение

from numpy import linalg

linalg.solve(a, b)

# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True